### ISSUE TITLE
max_size requires clarification for ODP_NONBLOCKING_LF and ODP_NONBLOCKING_WF

### ISSUE THREAD

**Issue by mvl-skardach** [OpenDataPlane/odp#826]
I've noticed that there is an undefined behavior for non-blocking queue types with relation to max_size. Unit tests expect it always to be bounded. This is different from the BLOCKING queue max_size logic.
See: https://github.com/OpenDataPlane/odp/blob/e3217b34b9741560443b972aea71e270b547e7d9/include/odp/api/spec/queue_types.h#L198

Question is whether max_size for non-blocking queue types can be non-bounded (`max_size == 0`) or not? If yes, then unit tests have to be aligned as currently they'll fail (burst size will be 0).

https://github.com/OpenDataPlane/odp/blob/e3217b34b9741560443b972aea71e270b547e7d9/test/validation/api/queue/queue.c#L473

**Comment by Bill-Fischofer-Personal** [comment]
Non-blocking queues are typically implemented as rings, which have a defined size. Blocking queues can be implemented as linked lists, which have no predefined upper limit (the limit is available storage). So `max_size` is a useful and convenient way to distinguish between these two cases. 

Since `max_size` is a `uint32_t` variable it may be sufficiently large to be effectively unbounded if an implementation had HW support for storage-limited non-blocking queues. In this case simply set `max_size` to `UINT_MAX`. In practice no performant application would have that many elements on a queue anyway, so the apparent limit would only be in theory.

**Comment by mvl-skardach** [comment]
@Bill-Fischofer-Personal Then information about setting UINT_MAX should be part of the doxygen for max_size.

**Comment by Bill-Fischofer-Personal** [comment]
That's implied since it's a valid value, but adding it would be a useful usage note.

**Comment by psavol** [comment]
/** Lock-free (ODP_NONBLOCKING_LF) implementation capabilities.
  * The specification is the same as for the blocking
  * implementation. */

I think the intention is that max_size works the same way on all three cases. I could clarify spec text and fix the test to ignore max_size if it's zero.

**Comment by mvl-skardach** [comment]
Works both ways for me as long as it's specified in the spec. :)
