### ISSUE TITLE
Multiple producer single consumer queue params

### ISSUE THREAD

**Issue by Neetika02** [OpenDataPlane/odp#997]
Hello,
I am very new to ODP. We are currently looking to enhance performance by porting existing LTE User Plane application to OFP/ODP-DPDK. In our architecture we need multiple producer single consumer queues. As per simple example tests we have found that the op_mode MT_UNSAFE gives a very high performance as compared to MT_SAFE. Can we use MT_UNSAFE even if there are multiple threads trying to enque into the queue at same time? Also, how can we use the nonblocking setting to our advantage. Are these queues similar to the ring library that DPDK provides. If not is there any way I can use the ring library of DPDK through ODP APIs?

**Comment by psavol** [comment]
/** Not multithread safe operation
 *
 * Queue operation (enqueue or dequeue) may not be multithread safe.
 * Application ensures synchronization between threads so that
 * simultaneously only single thread attempts the operation on
 * the same queue. */
ODP_QUEUE_OP_MT_UNSAFE

When application specifies that queue enq_mode/deq_mode may be MT_UNSAFE, it must not call the enq/deq operation simultaneously from multiple threads. MT_UNSAFE tells to the implementation that less locks/atomics is needed to protect the queue. This mode selection is per operation, so you can request e.g. a multi-producer / single-consumer queue with enq_mode=MT_SAFE + deq_mode=MT_UNSAFE. With that setting, multiple threads may call queue enqueue simultaneously, but only one thread (at a time) can call queue dequeue (for that queue).

Nonblocking setting is interesting when you need to ensure thread a thread blocked inside a queue operation cannot block other threads using the same queue. The default (ODP_BLOCKING) setting is more performant than nonblocking ones, when queues are implemented in SW. Where as, a HW based implementation may not care about this setting as it's always nonblocking.

These queues may be implemented with SW rings/lists or HW queues. ODP_DPDK does not utilize DPDK rings for these, but uses our own SW ring implementation (which is optimized for this API).

These queues are designed to pass events between HW and SW, or between SW threads. These event queues may be connected to the event scheduler as well. ODP has also stash API, which is targeted as a simple storage (LIFO or FIFO) of application specific object handles. Depending on the ODP implementation, stash may be implemented as a SW ring or HW pool.

**Comment by Neetika02** [comment]
Thanks a lot for the detailed reply. It helps a lot.
I will be using these queues between SW threads as you suggested with enq_mode as MT_SAFE and deq_mode as MT_UNSAFE. 
Could you please also help me with another thing. Is there any primitive that ODP provides for implementing a CAS instruction. e.g. If I want to keep a flag which will be read and set by different threads, I want to use a Test&Set type of instruction for accessing this flag as it will provide synchronized access in single cycle. So Is there any CAS primitive I can use to set a simple flag with value 0 or 1?

**Comment by JannePeltonen** [comment]
Yes. See atomic.h or https://opendataplane.github.io/odp/group__odp__atomic.html#ga9568820afe533a23dbdd8982ca6420cf

**Comment by Neetika02** [comment]
Thanks a lot for the help :)
